services:
  hotel_db:
    profiles:
      - db-only
      - local
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: hotel-db
    restart: unless-stopped
    ports:
      - '${DATABASE_PORT:?DATABASE_PORT env var is missing on .env file}:${DATABASE_PORT}'
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DATABASE_PASSWORD:?DATABASE_PASSWORD env var is missing on .env file}
      MSSQL_PID: "Developer"
    volumes:
      - sqlserver-data:/var/opt/mssql

  hotel_test_db:
    profiles:
      - test
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: hotel-test-db
    restart: unless-stopped
    ports:
      - '${TEST_DATABASE_PORT:?TEST_DATABASE_PORT env var is missing on .env file}:${TEST_DATABASE_PORT}'
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${TEST_DATABASE_PASSWORD:?TEST_DATABASE_PASSWORD env var is missing on .env file}
      MSSQL_PID: "Developer"
    volumes:
      - sqlserver-test-data:/var/opt/mssql

  hotel_api:
    profiles:
      - local
    build:
      context: .
      dockerfile: Dockerfile
    hostname: hotel-api
    restart: unless-stopped
    ports:
      - '${API_PORT:?API_PORT env var is missing on .env file}:${API_PORT}'
    env_file:
      - .env
    volumes:
      - ./src:/home/node/src
    depends_on:
      - hotel_db

volumes:
  sqlserver-data:
    driver: local
  sqlserver-test-data:
    driver: local
